### PR TITLE
Default search player inventory

### PR DESCRIPTION
**Pull request by aagrishankov**
This will allow players not to wait a long time for all items ".inv" search to be checked, so players can bind items immediately from inventory.

### CODE REVIEW

**Comment by aagrishankov** [comment]
image

**Comment by Prometheus0000** [comment]
Will this fix the extreme lag of having a couple put down (and used) in the same area?

**Comment by Prometheus0000** [comment]
NVM I'm thinking of the other player interface device.

**Comment by aagrishankov** [comment]
> Will this fix the extreme lag of having a couple put down (and used) in the same area?

you do not need to use a "searcher" as it immediately gives out all the player's inventory

**Comment by aagrishankov** [comment]
> NVM I'm thinking of the other player interface device.

oh.. okay

**Comment by aagrishankov** [comment]
sorry,  this not work in servers

**Pull request closed without merging**
