### PR TITLE
Move Steve's Addons ASM to explicit compat

### PR DESCRIPTION
**Pull request by ah-OOG-ah**
Move Steve's Addons ASM into code directly, with isModLoaded checks. Requires [this](https://github.com/GTNewHorizons/StevesAddons/pull/11) PR in Steve's Addons.
Additionally, minor license cleanup: the tweet screenshot is now directly in the repository and the license is in text as well.
Also, moves to Tags.java instead of token replacement in a file.

This doesn't load in nightly 310, and I have no idea why. Also, needs testing by people who use SFM.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@ah-OOG-ah on mod need the other code to load that is the problem. I am not sure how to setup this?

**Comment by ah-OOG-ah** [comment]
Merged into dev - seems to work now.

**Comment by ah-OOG-ah** [comment]
Should build and not break anything now.

**Comment by OneEyeMaker** [comment]
Instead of calling addon's methods from base mod (and so create circular dependency), it's better to create clear API that can be implemented/overridden in addon.
Also, don't use `Loader.isModLoaded` every time you want to call method from another mod: call it once and store result.

**Comment by ah-OOG-ah** [comment]
It's not really an API, it's specifically for Steve's Addons. However, it doesn't require Steve's Addons to compile, so no circular dep.

**Review by OneEyeMaker — APPROVED** [review]

**Pull request merged**
